---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

statusStyle: "dot"
language: "pt"
showStats: true
disableUpdateCheck: true

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
